name: 🚀 Feature Request
description: Suggest a new feature for the WinCC OA VS Code Extension
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
projects: ["mPokornyETM/3"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🎉
        
        Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocks current work)
        - High (Important for productivity)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the extension does this feature relate to?
      options:
        - Project Management (lifecycle, registration)
        - Code Editor (syntax, completion)
        - Testing & Quality (test execution, analysis)
        - Documentation (generation, templates)
        - Integration (API, CI/CD)
        - User Interface (tree view, dialogs)
        - Configuration (settings, preferences)
        - Other
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: "As a WinCC OA developer, I want [feature] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the extension currently works in this area
      placeholder: Describe the current state or limitations

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: Describe what you would like to see implemented

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might help us understand your request

  - type: dropdown
    id: winccoa-version
    attributes:
      label: WinCC OA Version
      description: Which WinCC OA version are you using?
      options:
        - "3.21"
        - "3.20"
        - "3.19"
        - "3.18"
        - "Multiple versions"
        - "Not applicable"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true